# Generated by Django 4.0.2 on 2022-04-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_image_alter_auctionlisting_imageurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='imageUrl',
            field=models.URLField(blank=True),
        ),
    ]
