# Generated by Django 4.0.2 on 2022-04-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_delete_image_alter_auctionlisting_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='is_same',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='yolo_pred_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='yolo_pred_percentage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
