# Generated by Django 4.0.2 on 2022-04-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctionlisting_is_same_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='is_same',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
