# Generated by Django 4.0.2 on 2022-04-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_auctionlisting_is_same'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='is_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='yolo_pred_percentage',
            field=models.IntegerField(blank=True, max_length=50),
        ),
    ]
