# Generated by Django 4.0.2 on 2022-04-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_auctionlisting_is_same_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='yolo_pred_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
